// react/src/app/app.component.jsx
// @flow
import React from 'react';
import { EntryForm } from './entry';

export class App extends React.Component<void, void, void> {
    render() {
        return (
            <section className="welcome">
                <h1>Welcome to JS Quest (React Version)</h1>
                <p>JS Quest is a hobby application made to help in aiding developers understand
                the differences between popular javascript development stacks. Oh, it's also a game
                about slaying orcs and getting eaten by grues.</p>
                <div className="welcome__entry">
                    <EntryForm />
                </div>
            </section>
        );
    }
}

// JsQuest.Client/src/app/app.component.ts
import { Component } from '@angular/core';
import { StoreLogMonitorComponent } from '@ngrx/store-log-monitor';
import { EntryFormComponent } from './players';

@Component({
    moduleId: module.id,
    selector: 'jsq-app',
    templateUrl: 'app.component.html',
    directives: [EntryFormComponent, StoreLogMonitorComponent]
})
export class AppComponent {
}

<section data-reactroot="" class="welcome"><h1>Welcome to JS Quest (Angular Version)</h1>
    <p>JS Quest is a hobby application made to help in aiding developers understand the differences between popular
        javascript development stacks. Oh, it's also a game about slaying orcs and getting eaten by grues.</p>
    <div class="welcome__entry">
        <jsq-entry-form placeholder="Say friend and enter..."></jsq-entry-form>
    </div>
  <ngrx-store-log-monitor toggleCommand="ctrl-t"></ngrx-store-log-monitor>
</section>
