// react/src/app/entry/EntryForm.component.jsx
// @flow
import React from 'react';
import autobind from 'autobind-decorator';
import classNames from 'classnames';

type Props = {
    placeholder: ?string
};

type DefaultProps = {
    placeholder: string,
}

type State = {
    username: string,
    errorMessage: ?string
};

type NameState = 'VALID' | 'MISSING' | 'TOO_SHORT';

const MIN_NAME_LENGTH = 3;

const errorText = {
    nameMissing: 'Please provide a username',
    nameTooShort: `Username must be at least ${MIN_NAME_LENGTH} characters`
};

@autobind
export class EntryForm extends React.Component<DefaultProps, Props, State> {
    static defaultProps: DefaultProps;
    props: Props;
    state: State;
    
    constructor(props: Props) {
        super(props);
        this.state = {
            username: '',
            errorMessage: null
        };
    }

    onFormSubmit(event: any) {
        const state: NameState = this.nameState(this.state.username);
        if (state !== 'VALID') {
            event.preventDefault();
            this.setError(state);
        }
    }

    onNameEntry(event: any) {
        const username = event.target.value;
        this.setState({ username });
    }
    
    setError(nameState: NameState) {
        switch(nameState) {
            case 'MISSING': 
                this.setState({ errorMessage: errorText.nameMissing });
                break;
            case 'TOO_SHORT':
                this.setState({ errorMessage: errorText.nameTooShort });
                break;
            default:
                return;
        }
    }

    nameState(value: string): NameState {
        if (!value || value === '') {
            return 'MISSING';
        }

        if (value.length < MIN_NAME_LENGTH) {
            return 'TOO_SHORT';
        }
        
        return 'VALID';
    }
    
    render() {
        let errorClass = classNames({
            'entry-form__errmsg': true,
            'is-shown': this.state.errorMessage
        });
        
        return (
            <form className="entry-form" noValidate="" onSubmit={this.onFormSubmit}>
                <input 
                    type="text" 
                    value={this.state.username}
                    placeholder={this.props.placeholder}
                    onChange={this.onNameEntry}
                />
                <button type="submit">Enter Game</button>
                <span className={errorClass}>
                    {this.state.errorMessage}
                </span>
            </form>
        );
    }
}

EntryForm.defaultProps = {
    placeholder: 'Enter your name...'
};

// JsQuest.Client/src/app/players/entry-form/entry-form.component.ts
import {Component, Input, OnInit} from '@angular/core';
import { NgClass } from '@angular/common';
import { Store } from '@ngrx/store';
import { AppState } from '../../reducers';
import { PlayerActions } from '../players.actions';
import {
    REACTIVE_FORM_DIRECTIVES,
    AbstractControl,
    FormBuilder,
    FormGroup,
    Validators
} from '@angular/forms';
import {Observable} from 'rxjs';

@Component({
    moduleId: module.id,
    selector: 'jsq-entry-form',
    templateUrl: 'entry-form.component.html',
    directives: [NgClass, REACTIVE_FORM_DIRECTIVES]
})
export class EntryFormComponent implements OnInit {

    static errorText = {
        nameMissing: 'Please provide a username',
        nameTooShort: 'Username must be at least 3 characters'
    };

    private static buildUserForm(formBuilder: FormBuilder) {
        return formBuilder.group({
            username: ['', EntryFormComponent.usernameValidators()]
        });
    }

    private static usernameValidators() {
        return Validators.compose([Validators.required, Validators.minLength(3)]);
    }

    @Input() placeholder: string;

    userForm: FormGroup;
    usernameInput: AbstractControl;
    errorMessage: string;
    players$: Observable<any>;

    constructor(public store: Store<AppState>, formBuilder: FormBuilder) {
        this.players$ = store.select('players');
        this.userForm = EntryFormComponent.buildUserForm(formBuilder);
        this.usernameInput = this.userForm.controls['username'];
    }

    ngOnInit() {
        this.placeholder = this.placeholder || 'Enter your name...';
    }

    onFormSubmit() {
        if (!this.usernameInput.valid) {
            this.errorMessage = this.getErrorMessage();
        }

        this.store.dispatch({ type: PlayerActions.SEARCH, payload: this.usernameInput.value });
    }


    private getErrorMessage() {
        if (this.usernameInput.errors['required']) {
            return EntryFormComponent.errorText.nameMissing;
        }

        if (this.usernameInput.errors['minlength']) {
            return EntryFormComponent.errorText.nameTooShort;
        }

        return;
    }
}

<form class="entry-form"
      [formGroup]="userForm"
      (ngSubmit)="onFormSubmit($event)">
    <input type="text"
           placeholder="{{placeholder}}"
           [formControl]="usernameInput">
    <button type="submit">Enter Game</button>
    <span class="entry-form__errmsg"
          [ngClass]="{ 'is-shown': errorMessage }">
        {{errorMessage}}
    </span>
</form>
